//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabKit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HabKit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;layout name=&quot;badge_details&quot; width=&quot;20&quot; height=&quot;20&quot; version=&quot;0.0&quot;&gt;
        ///  &lt;window&gt;
        ///    &lt;border x=&quot;87&quot; y=&quot;53&quot; width=&quot;263&quot; height=&quot;99&quot; params=&quot;0&quot; style=&quot;0&quot; name=&quot;test&quot;&gt;
        ///      &lt;children&gt;
        ///        &lt;text x=&quot;8&quot; y=&quot;6&quot; width=&quot;250&quot; height=&quot;28&quot; params=&quot;16&quot; style=&quot;0&quot; name=&quot;name&quot; caption=&quot;&quot;&gt;
        ///          &lt;variables&gt;
        ///            &lt;var key=&quot;font_face&quot; value=&quot;Volter Bold&quot; type=&quot;String&quot;/&gt;
        ///            &lt;var key=&quot;font_size&quot; value=&quot;9&quot; type=&quot;uint&quot;/&gt;
        ///            &lt;var key=&quot;text_color&quot; value=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Badge_Details {
            get {
                return ResourceManager.GetString("Badge_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;layout name=&quot;furni_view&quot; width=&quot;429&quot; height=&quot;497&quot; version=&quot;0.1&quot; uid=&quot;7093FB25-BA90-F4A0-8830-2C0B7A06AAF6&quot;&gt;
        ///  &lt;window&gt;
        ///    &lt;itemlist_vertical x=&quot;0&quot; y=&quot;0&quot; width=&quot;429&quot; height=&quot;497&quot; params=&quot;16&quot; style=&quot;0&quot;&gt;
        ///      &lt;children&gt;
        ///        &lt;border x=&quot;0&quot; y=&quot;0&quot; width=&quot;190&quot; height=&quot;390&quot; params=&quot;16&quot; style=&quot;1&quot; name=&quot;info_border&quot;&gt;
        ///          &lt;children&gt;
        ///            &lt;closebutton x=&quot;168&quot; y=&quot;6&quot; width=&quot;18&quot; height=&quot;16&quot; params=&quot;17&quot; style=&quot;1&quot; background=&quot;true&quot; treshold=&quot;0&quot; tags=&quot;close&quot;/&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Furni_View {
            get {
                return ResourceManager.GetString("Furni_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;layout name=&quot;userview_test&quot; width=&quot;1036&quot; height=&quot;400&quot; version=&quot;0.1&quot; uid=&quot;BD864F62-5EDC-04E7-B48A-62EEE6AC8D58&quot;&gt;
        ///  &lt;window&gt;
        ///    &lt;itemlist_vertical x=&quot;0&quot; y=&quot;0&quot; width=&quot;1036&quot; height=&quot;400&quot; params=&quot;16&quot; style=&quot;0&quot;&gt;
        ///      &lt;children&gt;
        ///        &lt;border x=&quot;0&quot; y=&quot;0&quot; width=&quot;190&quot; height=&quot;357&quot; params=&quot;17&quot; style=&quot;1&quot; name=&quot;info_border&quot;&gt;
        ///          &lt;children&gt;
        ///            &lt;bitmap x=&quot;8&quot; y=&quot;11&quot; width=&quot;16&quot; height=&quot;15&quot; params=&quot;17&quot; style=&quot;0&quot; name=&quot;home_icon&quot; treshold=&quot;0&quot;/&gt;
        ///            &lt;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserView_Test {
            get {
                return ResourceManager.GetString("UserView_Test", resourceCulture);
            }
        }
    }
}
